# Generated by Django 4.0.1 on 2022-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
